1. ![image](https://user-images.githubusercontent.com/64036955/128819481-b27567fd-62a3-48ec-93a5-798760ae4986.png)
What to do:  
- Control panel->python-> repair.
 This error isn't encountered now, but rasa is not found as an external / internal command.  
 ‚ùópython version 3.9 not compatible   
 What to do: Install python version 3.8 (or any version from 3.6x to 3.8x) and add to path.
 
 2. Using  rasa x :   
  use the command :
 
      rasa x --enable-api   
   
   
   ![image](https://user-images.githubusercontent.com/64036955/132681666-fa69c095-ba4a-4b29-9557-89e558f846d1.png)

- To avoid the error exception calling callback for...
     
